---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: shortlet-tls
  namespace: shortlet
spec:
  secretName: shortlet-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: timeapi.nayokians.me
  dnsNames:
    - timeapi.nayokians.me
