# Service script to expose session database
---
apiVersion: v1
kind: Service
metadata:
  name: session-db-svc
  labels:
    name: session-db
  namespace: shortlet
spec:
  ports:
    # the port that this service should serve on
  - port: 6379
    targetPort: 6379
  selector:
    name: session-db
