# Deployment script for timeserver-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeserver-api
  namespace: shortlet
spec:
  replicas: 1
  selector:
    matchLabels:
      name: timeserver-api
  template:
    metadata:
      labels:
        name: timeserver-api
    spec:
      containers:
      - name: timeserver-api
        image: ikuku1010/shortlet-api:1.21
        resources:
          limits:
            cpu: 300m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 300Mi
        ports:
        - name: http
          containerPort: 8000
        env:
        - name: SESSION_REDIS
          value: "true"
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 3
      nodeSelector:
        kubernetes.io/os: linux
